### ISSUE TITLE
modify -b argument into a -e argument to specify a list of earfcns

### ISSUE THREAD

**Issue by cooperq** [EFForg/srsLTE#6]
In our new scanning code ( lib/examples/cell_measurement.cc ) we have a mandatory -b argument that specifies the band to scan. This should be replaced with something like -e which specifies a list of EARFCNs to scan. 
Example usage:
`./cell_measurement -e 125,800,820,1200`

An argument like this can be parsed by splitting along the commas into a c++ vector. 
This exact thing is done in https://github.com/EFForg/srsLTE/blob/master/srsue/src/ue.cc#L155-L170

**Comment by void-elf** [comment]
completed in https://github.com/EFForg/srsLTE/commit/11826331ddfcb66cb95d6a7ac2ea2926a09cd1d6
